# Site settings
title: "Nicolas' Numerical Algebra Blog"
description: >-
  A documentation of my journey in Numerical Algebra, keeping track of paper implementations, explanations, and personal code.

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Enable MathJax for LaTeX support
math: mathjax

# Just the Docs settings
aux_links:
  "My GitHub":
    - "https://github.com/otiumoftlon"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
